backend:
  name: git-gateway
  branch: main

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "image", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "literatura"
    label: "Literatura"
    folder: "content/literatura"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen Destacada", name: "image", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "podcast"
    label: "Podcast"
    folder: "content/podcast"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Imagen del Episodio", name: "image", widget: "image" }
      - { label: "Audio (URL o Código)", name: "audio", widget: "string" }
      - { label: "Descripción", name: "body", widget: "markdown" }
