backend:
  name: git-gateway
  branch: gh-pages

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog/el-opinista"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Resumen", name: "summary", widget: "string" }
      - { label: "Imagen Destacada", name: "featured", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "podcast"
    label: "Podcast"
    folder: "content/podcast"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Resumen", name: "summary", widget: "string" }
      - { label: "Imagen Destacada", name: "featured", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "literatura"
    label: "Literatura"
    folder: "content/literatura"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Resumen", name: "summary", widget: "string" }
      - { label: "Imagen Destacada", name: "featured", widget: "image" }
      - { label: "Contenido", name: "body", widget: "markdown" }
